spring:
  datasource:
    url: ${jdbcURL}
    password: ${jdbcPassword}
    username: ${jdbcUsername}

  jpa:

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

jwt:
  secret:
    key: ${jwtSecretKey}
